# -*- mode: ruby -*-
# Vagrant makefile for Digital Ocean

DO_TOKEN ='' # Important!
hostname = '' # Name of the host and VM
ram = '512'
SSH_KEY_NAME = ''
DISTR = 'ubuntu-14-10-x64' # vagrant digitalocean-list images TOKEN
REGION = 'lon1'

Vagrant.configure(2) do |config|
  config.vm.host_name = hostname

  # If need port forwarding
  # One ports
  #config.vm.network "forwarded_port", guest: 5000, host: 5000,
  #  auto_correct: true

  # Stack of port
  #for i in 64000..64010
  #  config.vm.network :forwarded_port, guest: i, host: i
  #end

  # Load startup script
  config.vm.provision "shell", path: "bootstrap.sh"

  # Share folder inside '/vagrant'
  #config.vm.synced_folder "./www/", "/var/www", create: true, group: "www-data", owner: "www-data"

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    provider.ssh_key_name = SSH_KEY_NAME
    provider.token = DO_TOKEN
    provider.image = DISTR
    provider.region = REGION
    provider.size = ram + 'mb'
  end

end