# -*- mode: ruby -*-
# Vagrant makefile for VirtualBox

box = 'Ubuntu/trusty64' # If need other Box, look at https://vagrantcloud.com/boxes/search and http://www.vagrantbox.es
hostname = ''
ram = '512'

Vagrant.configure(2) do |config|
  config.vm.box = box
  config.vm.host_name = hostname

  # If need port forwarding
  config.vm.network "forwarded_port", guest: 5000, host: 5000,
    auto_correct: true

  # Load startup script
  config.vm.provision "shell", path: "bootstrap.sh"

  # Share folder inside '/vagrant'
  config.vm.synced_folder "./www/", "/var/www", create: true, group: "www-data", owner: "www-data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = ram
    vb.name = hostname
  end
end